concurrency:
  cancel-in-progress: true
  group: gradle
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean assemble --info --stacktrace --no-daemon
    - continue-on-error: true
      name: Test with Gradle Jacoco and Coveralls
      run: ./gradlew test jacocoTestReport coveralls --no-daemon
    - continue-on-error: true
      name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        debug: true
        file: build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
        format: jacoco
        github-token: ${{ secrets.GITHUB_TOKEN }}
  docker-build:
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create more disk space
      run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost"
        && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: docker_build
      name: Build and push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        dockerfile: Dockerfile.crf
        image: lfoppiano/grobid
        password: ${{ secrets.DOCKERHUB_TOKEN_LFOPPIANO }}
        pushImage: ${{ github.event_name != 'pull_request' }}
        registry: docker.io
        tags: latest-develop
        username: ${{ secrets.DOCKERHUB_USERNAME_LFOPPIANO }}
    - continue-on-error: true
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
name: Build unstable
on:
  repository_dispatch:
    types: trigger-ga___ci-build-unstable.yml
